FROM mcr.microsoft.com/playwright:v1.35.1-jammy as playwright

ARG DEBIAN_FRONTEND=noninteractive
ARG TZ=America/New_York
ARG DOCKER_IMAGE_NAME_TEMPLATE="storj-qa/playwright:v1.35.1-jammy"

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright

FROM  golang:1.20.1 AS SJ-Build

WORKDIR /go/ci

COPY ./deps.sh deps.sh
RUN bash deps.sh

COPY ./slim.sh slim.sh
RUN bash slim.sh

COPY ./git-uitests.sh git-uitests.sh
RUN bash git-uitests.sh
